In [68]:
import numpy as np


In [69]:
lista = range(1,11)
lista


range(1, 11)

In [70]:
arreglo = np.array(lista)


In [71]:
arreglo.dtype

dtype('int32')

In [72]:
np.array(arreglo,dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [73]:
arreglonuevo= np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arreglonuevo2= np.arange(1,11,2)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3 style="color:blue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h3>

Bibliotecas, Numpy, Random, Pandas

Funciones con numpy

In [75]:
#Argmax() - argmin() (OBTIENE LA POSICION DEL VALOR MAXIMO Y MINIMO RESPECTIVAMENTE)

In [76]:
#dtype (Funcion que consulta un tipo de dato)

In [77]:
#Arange (Genera numeros secuenciales de uno a n)

In [78]:
#Generacion de arreglos

arreglodeunos=np.ones(10)
arreglodeunos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [79]:
#Transformando el arreglo de 1 de punto flotante a enteros

arreglo_int_ones = arreglodeunos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [80]:
#Arreglo de ceros
arreglodeceros= np.zeros(5)
arreglodeceros

array([0., 0., 0., 0., 0.])

In [81]:
import random as np

In [ ]:
#Generar un arreglo aleatorio
arreglo_aleatorio=np.random.rand(5)


In [ ]:
arreglo_aleatorio_2= np.random.radint(1,101,5)

Generando un array de 9 elementos

In [ ]:
matriz=np.random.rand(3,3)
matriz
#(Alineacion de listas/arreglos)

Generando una matriz aleatoria de numeros aleatorios enteros del 1 al 100

In [ ]:
Matriz2=np.random.radint(1,101,(10,10)) #(X,X) X1= FILAS X2= Columnas